"""initial_schema

Revision ID: 973d81851aeb
Revises:
Create Date: 2026-08-24 11:44:19.756259
"""
from __future__ import annotations

from alembic import op
import gen_epix.fastapp.repositories.sa.util
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '973d81851aeb'
down_revision = None
branch_labels = None
depends_on = None


def _create_schemas() -> None:
    if op.get_bind().dialect.name == "mssql":
        for schema in ("abac", "organization", "system", "file", "seq"):
            op.execute(
                sa.text(
                    f"IF SCHEMA_ID('{schema}') IS NULL "
                    f"EXEC('CREATE SCHEMA [{schema}]')"
                )
            )


def upgrade() -> None:
    _create_schemas()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_collection',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_name'),
    schema='organization'
    )
    op.create_table('data_collection_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_set_name'),
    schema='organization'
    )
    op.create_table('identifier_issuer',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_identifier_issuer_code'),
    schema='organization'
    )
    op.create_table('organization',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organization_code'),
    sa.UniqueConstraint('name', name='uq_organization_name'),
    schema='organization'
    )
    op.create_table('organization_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_organization_set_name'),
    schema='organization'
    )
    op.create_table('data_collection_set_member',
    sa.Column('data_collection_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['data_collection_id'], ['organization.data_collection.id'], name='fk_data_collection_set_member_data_collection_id'),
    sa.ForeignKeyConstraint(['data_collection_set_id'], ['organization.data_collection_set.id'], name='fk_data_collection_set_member_data_collection_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_collection_set_id', 'data_collection_id', name='uq_data_collection_set_member_data_collection_set_id_data_collection_id'),
    schema='organization'
    )
    op.create_table('organization_identifier_issuer_link',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['identifier_issuer_id'], ['organization.identifier_issuer.id'], name='fk_organization_identifier_issuer_link_identifier_issuer_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_identifier_issuer_link_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'identifier_issuer_id', name='uq_organization_identifier_issuer_link_organization_id_identifier_issuer_id'),
    schema='organization'
    )
    op.create_table('organization_set_member',
    sa.Column('organization_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_set_member_organization_id'),
    sa.ForeignKeyConstraint(['organization_set_id'], ['organization.organization_set.id'], name='fk_organization_set_member_organization_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_set_id', 'organization_id', name='uq_organization_set_member_organization_set_id_organization_id'),
    schema='organization'
    )
    op.create_table('site',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_site_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_site_organization_id_name'),
    schema='organization'
    )
    op.create_table('user',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_user_key'),
    schema='organization'
    )
    op.create_table('contact',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('site_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['organization.site.id'], name='fk_contact_site_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_contact_site_id_name'),
    schema='organization'
    )
    op.create_table('user_invitation',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('invited_by_user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['organization.user.id'], name='fk_user_invitation_invited_by_user_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_invitation_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'expires_at', name='uq_user_invitation_key_expires_at'),
    schema='organization'
    )
    op.create_table('organization_admin_policy',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_admin_policy_organization_id_user_id'),
    schema='abac'
    )
    op.create_table('outage',
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('visible_from', sa.DateTime(), nullable=True),
    sa.Column('visible_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    op.create_table('file',
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='file'
    )
    op.create_table('locus',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locus_type', sa.Enum('GENE', 'INTERGENIC_REGION', 'TANDEM_REPEAT', 'PCR', 'OTHER', 'UNKNOWN', name='locustype'), nullable=True),
    sa.Column('gene_product_code', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_locus_code'),
    schema='seq'
    )
    op.create_table('locus_code_map',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('code_map', sa.JSON(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_locus_code_map_code'),
    schema='seq'
    )
    op.create_table('locus_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('n_loci', sa.Integer(), nullable=False),
    sa.Column('locus_ids', sa.JSON(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_locus_set_code'),
    sa.UniqueConstraint('name', name='uq_locus_set_name'),
    schema='seq'
    )
    op.create_table('protocol_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_protocol_set_code'),
    sa.UniqueConstraint('name', name='uq_protocol_set_name'),
    schema='seq'
    )
    op.create_table('sample',
    sa.Column('created_in_data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='seq'
    )
    op.create_table('seq_category_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_seq_category_set_code'),
    sa.UniqueConstraint('name', name='uq_seq_category_set_name'),
    schema='seq'
    )
    op.create_table('taxon',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Enum('NO_RANK', 'ACELLULAR_ROOT', 'REALM', 'DOMAIN', 'SUPERKINGDOM', 'KINGDOM', 'SUBKINGDOM', 'PHYLUM', 'SUBPHYLUM', 'SUPERCLASS', 'CLASS', 'SUBCLASS', 'INFRACLASS', 'ORDER', 'SUBORDER', 'FAMILY', 'SUBFAMILY', 'GENUS', 'SUBGENUS', 'SPECIES_GROUP', 'SPECIES_SUBGROUP', 'SPECIES', 'SEROGROUP', 'SEROTYPE', 'BIOTYPE', 'VARIETAS', 'FORMA_SPECIALIS', 'SUBSPECIES', 'GENOTYPE', 'STRAIN', 'CLADE', 'TRIBE', 'ISOLATE', name='taxonrank'), nullable=False),
    sa.Column('ncbi_taxid', sa.Integer(), nullable=True),
    sa.Column('ictv_ictv_id', sa.String(length=255), nullable=True),
    sa.Column('snomed_sctid', sa.Integer(), nullable=True),
    sa.Column('ncbi_ancestor_taxids', sa.JSON(), nullable=True),
    sa.Column('ancestor_taxon_ids', sa.JSON(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_taxon_code'),
    schema='seq'
    )
    op.create_table('taxon_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_taxon_set_code'),
    sa.UniqueConstraint('name', name='uq_taxon_set_name'),
    schema='seq'
    )
    op.create_table('tree_algorithm_class',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_seq_based', sa.Boolean(), nullable=False),
    sa.Column('is_dist_based', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tree_algorithm_class_code'),
    sa.UniqueConstraint('name', name='uq_tree_algorithm_class_name'),
    schema='seq'
    )
    op.create_table('allele',
    sa.Column('locus_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('seq', sa.Text(), nullable=False),
    sa.Column('seq_format', sa.Enum('HASH_ONLY', 'STR_DNA', 'STR_DNA_INCL_GAP', 'NEXTCLADE', name='seqformat'), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locus_id'], ['seq.locus.id'], name='fk_allele_locus_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='seq'
    )
    op.create_table('ref_allele',
    sa.Column('locus_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('seq', sa.Text(), nullable=False),
    sa.Column('seq_format', sa.Enum('HASH_ONLY', 'STR_DNA', 'STR_DNA_INCL_GAP', 'NEXTCLADE', name='seqformat'), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locus_id'], ['seq.locus.id'], name='fk_ref_allele_locus_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locus_id', 'index', name='uq_ref_allele_locus_id_index'),
    schema='seq'
    )
    op.create_table('ref_seq',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('taxon_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('genbank_accession_code', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('seq', sa.Text(), nullable=False),
    sa.Column('seq_format', sa.Enum('HASH_ONLY', 'STR_DNA', 'STR_DNA_INCL_GAP', 'NEXTCLADE', name='seqformat'), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['seq.taxon.id'], name='fk_ref_seq_taxon_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ref_seq_code'),
    sa.UniqueConstraint('name', name='uq_ref_seq_name'),
    schema='seq'
    )
    op.create_table('sample_data_collection_link',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_sample_data_collection_link_sample_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'data_collection_id', name='uq_sample_data_collection_link_sample_id_data_collection_id'),
    schema='seq'
    )
    op.create_table('sample_identifier',
    sa.Column('internal_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['internal_id'], ['seq.sample.id'], name='fk_sample_identifier_internal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_issuer_id', 'external_id', name='uq_sample_identifier_identifier_issuer_id_external_id'),
    schema='seq'
    )
    op.create_table('seq_category',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('seq_category_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['seq_category_set_id'], ['seq.seq_category_set.id'], name='fk_seq_category_seq_category_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_seq_category_code'),
    sa.UniqueConstraint('name', name='uq_seq_category_name'),
    schema='seq'
    )
    op.create_table('taxon_set_member',
    sa.Column('taxon_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('taxon_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['taxon_id'], ['seq.taxon.id'], name='fk_taxon_set_member_taxon_id'),
    sa.ForeignKeyConstraint(['taxon_set_id'], ['seq.taxon_set.id'], name='fk_taxon_set_member_taxon_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxon_id', name='uq_taxon_set_member_taxon_id'),
    sa.UniqueConstraint('taxon_set_id', name='uq_taxon_set_member_taxon_set_id'),
    schema='seq'
    )
    op.create_table('tree_algorithm',
    sa.Column('code', sa.Enum('SLINK', 'CLINK', 'UPGMA', 'WPGMA', 'UPGMC', 'WPGMC', 'VERSATILE', 'MISSQ', 'MNSSQ', 'MIVAR', 'MNVAR', 'MINI_MAX', 'HAUSDORFF', 'MIN_SUM_MEDOID', 'MIN_SUM_INCREASE_MEDOID', 'MEDOID', 'MIN_ENERGY', 'FITCH_MARGOLIASH', 'MAX_PARSIMONY', 'ML', 'BAYESIAN_INFERENCE', 'MIN_SPANNING', 'NJ', name='treealgorithm'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tree_algorithm_class_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_ultrametric', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['tree_algorithm_class_id'], ['seq.tree_algorithm_class.id'], name='fk_tree_algorithm_tree_algorithm_class_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tree_algorithm_code'),
    sa.UniqueConstraint('name', name='uq_tree_algorithm_name'),
    schema='seq'
    )
    op.create_table('protocol',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('protocol_type', sa.Enum('PCR_MEASUREMENT', 'AST_MEASUREMENT', 'SEQUENCING', 'ASSEMBLY', 'TAXONOMY', 'SEQ_CLASSIFICATION', 'SEQ_PROFILE', 'SEQ_DISTANCE', 'AST_PREDICTION', name='protocoltype'), nullable=False),
    sa.Column('git_repository_uri', sa.String(length=2000), nullable=True),
    sa.Column('git_commit_hash', sa.String(length=40), nullable=True),
    sa.Column('git_commit_tag', sa.String(length=255), nullable=True),
    sa.Column('valid_start_datetime', sa.DateTime(), nullable=True),
    sa.Column('valid_end_datetime', sa.DateTime(), nullable=True),
    sa.Column('ref_seq_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('seq_category_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('locus_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('seq_profile_type', sa.Enum('SNP', 'LOCUS', 'ALLELE', 'MLVA', 'KMER', name='seqprofiletype'), nullable=True),
    sa.Column('seq_distance_type', sa.Enum('SNP_HAMMING', 'ALLELE_HAMMING', 'MLVA_HAMMING', 'MLVA_EUCLIDEAN', 'KMER_EUCLIDEAN', name='seqdistancetype'), nullable=True),
    sa.Column('is_integer_distance', sa.Boolean(), nullable=True),
    sa.Column('max_stored_distance', sa.Float(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['locus_set_id'], ['seq.locus_set.id'], name='fk_protocol_locus_set_id'),
    sa.ForeignKeyConstraint(['ref_seq_id'], ['seq.ref_seq.id'], name='fk_protocol_ref_seq_id'),
    sa.ForeignKeyConstraint(['seq_category_set_id'], ['seq.seq_category_set.id'], name='fk_protocol_seq_category_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_protocol_code'),
    schema='seq'
    )
    op.create_table('ast_measurement',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_ast_measurement_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_ast_measurement_sample_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'protocol_id', name='uq_ast_measurement_sample_id_protocol_id'),
    schema='seq'
    )
    op.create_table('pcr_measurement',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_pcr_measurement_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_pcr_measurement_sample_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'protocol_id', name='uq_pcr_measurement_sample_id_protocol_id'),
    schema='seq'
    )
    op.create_table('protocol_set_member',
    sa.Column('protocol_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_protocol_set_member_protocol_id'),
    sa.ForeignKeyConstraint(['protocol_set_id'], ['seq.protocol_set.id'], name='fk_protocol_set_member_protocol_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_set_id', 'protocol_id', name='uq_protocol_set_member_protocol_set_id_protocol_id'),
    schema='seq'
    )
    op.create_table('read_set',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('fwd_uri', sa.Text(), nullable=True),
    sa.Column('rev_uri', sa.Text(), nullable=True),
    sa.Column('fwd_file_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('rev_file_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('file_format', sa.Enum('FASTQ', name='readsfileformat'), nullable=True),
    sa.Column('file_compression', sa.Enum('NONE', 'GZIP', name='filecompression'), nullable=True),
    sa.Column('fwd_reads_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('rev_reads_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('sequencing_run_code', sa.String(length=255), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_read_set_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_read_set_sample_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='seq'
    )
    op.create_table('read_set_identifier',
    sa.Column('internal_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['internal_id'], ['seq.read_set.id'], name='fk_read_set_identifier_internal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_issuer_id', 'external_id', name='uq_read_set_identifier_identifier_issuer_id_external_id'),
    schema='seq'
    )
    op.create_table('seq',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('file_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('file_format', sa.Enum('FASTA', name='seqfileformat'), nullable=True),
    sa.Column('file_compression', sa.Enum('NONE', 'GZIP', name='filecompression'), nullable=True),
    sa.Column('file_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('read_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('read_set2_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('contigs', sa.JSON(), nullable=True),
    sa.Column('seq_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('n_contigs', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('max_contig_length', sa.Integer(), nullable=False),
    sa.Column('min_contig_length', sa.Integer(), nullable=False),
    sa.Column('median_contig_length', sa.Float(), nullable=False),
    sa.Column('n50', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_seq_protocol_id'),
    sa.ForeignKeyConstraint(['read_set2_id'], ['seq.read_set.id'], name='fk_seq_read_set2_id'),
    sa.ForeignKeyConstraint(['read_set_id'], ['seq.read_set.id'], name='fk_seq_read_set_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_seq_sample_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'read_set_id', 'read_set2_id', 'protocol_id', name='uq_seq_sample_id_read_set_id_read_set2_id_protocol_id'),
    schema='seq'
    )
    op.create_index(op.f('ix_seq_seq_sample_id'), 'seq', ['sample_id'], unique=False, schema='seq')
    op.create_table('ast_prediction',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_ast_prediction_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_ast_prediction_sample_id'),
    sa.ForeignKeyConstraint(['seq_id'], ['seq.seq.id'], name='fk_ast_prediction_seq_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq_id', 'protocol_id', name='uq_ast_prediction_seq_id_protocol_id'),
    schema='seq'
    )
    op.create_table('seq_classification',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('primary_category_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['primary_category_id'], ['seq.seq_category.id'], name='fk_seq_classification_primary_category_id'),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_seq_classification_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_seq_classification_sample_id'),
    sa.ForeignKeyConstraint(['seq_id'], ['seq.seq.id'], name='fk_seq_classification_seq_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq_id', 'protocol_id', name='uq_seq_classification_seq_id_protocol_id'),
    schema='seq'
    )
    op.create_index(op.f('ix_seq_seq_classification_sample_id'), 'seq_classification', ['sample_id'], unique=False, schema='seq')
    op.create_index(op.f('ix_seq_seq_classification_seq_id'), 'seq_classification', ['seq_id'], unique=False, schema='seq')
    op.create_table('seq_identifier',
    sa.Column('internal_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['internal_id'], ['seq.seq.id'], name='fk_seq_identifier_internal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_issuer_id', 'external_id', name='uq_seq_identifier_identifier_issuer_id_external_id'),
    schema='seq'
    )
    op.create_table('seq_profile',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_profile_type', sa.Enum('SNP', 'LOCUS', 'ALLELE', 'MLVA', 'KMER', name='seqprofiletype'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_seq_profile_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_seq_profile_sample_id'),
    sa.ForeignKeyConstraint(['seq_id'], ['seq.seq.id'], name='fk_seq_profile_seq_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='seq'
    )
    op.create_index(op.f('ix_seq_seq_profile_sample_id'), 'seq_profile', ['sample_id'], unique=False, schema='seq')
    op.create_table('seq_taxonomy',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('primary_taxon_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.Column('qc_result', sa.Enum('PENDING', 'FAIL', 'WARN', 'PASS', name='qualitycontrolresult'), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_report', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['primary_taxon_id'], ['seq.taxon.id'], name='fk_seq_taxonomy_primary_taxon_id'),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_seq_taxonomy_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_seq_taxonomy_sample_id'),
    sa.ForeignKeyConstraint(['seq_id'], ['seq.seq.id'], name='fk_seq_taxonomy_seq_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', name='uq_seq_taxonomy_protocol_id'),
    sa.UniqueConstraint('seq_id', name='uq_seq_taxonomy_seq_id'),
    schema='seq'
    )
    op.create_index(op.f('ix_seq_seq_taxonomy_sample_id'), 'seq_taxonomy', ['sample_id'], unique=False, schema='seq')
    op.create_index(op.f('ix_seq_seq_taxonomy_seq_id'), 'seq_taxonomy', ['seq_id'], unique=False, schema='seq')
    op.create_table('seq_distance',
    sa.Column('sample_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seq_profile_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('format', sa.Integer(), nullable=False),
    sa.Column('content_hash', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content2', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_id'], ['seq.protocol.id'], name='fk_seq_distance_protocol_id'),
    sa.ForeignKeyConstraint(['sample_id'], ['seq.sample.id'], name='fk_seq_distance_sample_id'),
    sa.ForeignKeyConstraint(['seq_profile_id'], ['seq.seq_profile.id'], name='fk_seq_distance_seq_profile_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocol_id', 'seq_profile_id', name='uq_seq_distance_protocol_id_seq_profile_id'),
    schema='seq'
    )
    op.create_index(op.f('ix_seq_seq_distance_protocol_id'), 'seq_distance', ['protocol_id'], unique=False, schema='seq')
    op.create_index(op.f('ix_seq_seq_distance_sample_id'), 'seq_distance', ['sample_id'], unique=False, schema='seq')
    op.create_index(op.f('ix_seq_seq_distance_seq_profile_id'), 'seq_distance', ['seq_profile_id'], unique=False, schema='seq')
    op.create_table('seq_profile_identifier',
    sa.Column('internal_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['internal_id'], ['seq.seq_profile.id'], name='fk_seq_profile_identifier_internal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_issuer_id', 'external_id', name='uq_seq_profile_identifier_identifier_issuer_id_external_id'),
    schema='seq'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seq_profile_identifier', schema='seq')
    op.drop_index(op.f('ix_seq_seq_distance_seq_profile_id'), table_name='seq_distance', schema='seq')
    op.drop_index(op.f('ix_seq_seq_distance_sample_id'), table_name='seq_distance', schema='seq')
    op.drop_index(op.f('ix_seq_seq_distance_protocol_id'), table_name='seq_distance', schema='seq')
    op.drop_table('seq_distance', schema='seq')
    op.drop_index(op.f('ix_seq_seq_taxonomy_seq_id'), table_name='seq_taxonomy', schema='seq')
    op.drop_index(op.f('ix_seq_seq_taxonomy_sample_id'), table_name='seq_taxonomy', schema='seq')
    op.drop_table('seq_taxonomy', schema='seq')
    op.drop_index(op.f('ix_seq_seq_profile_sample_id'), table_name='seq_profile', schema='seq')
    op.drop_table('seq_profile', schema='seq')
    op.drop_table('seq_identifier', schema='seq')
    op.drop_index(op.f('ix_seq_seq_classification_seq_id'), table_name='seq_classification', schema='seq')
    op.drop_index(op.f('ix_seq_seq_classification_sample_id'), table_name='seq_classification', schema='seq')
    op.drop_table('seq_classification', schema='seq')
    op.drop_table('ast_prediction', schema='seq')
    op.drop_index(op.f('ix_seq_seq_sample_id'), table_name='seq', schema='seq')
    op.drop_table('seq', schema='seq')
    op.drop_table('read_set_identifier', schema='seq')
    op.drop_table('read_set', schema='seq')
    op.drop_table('protocol_set_member', schema='seq')
    op.drop_table('pcr_measurement', schema='seq')
    op.drop_table('ast_measurement', schema='seq')
    op.drop_table('protocol', schema='seq')
    op.drop_table('tree_algorithm', schema='seq')
    op.drop_table('taxon_set_member', schema='seq')
    op.drop_table('seq_category', schema='seq')
    op.drop_table('sample_identifier', schema='seq')
    op.drop_table('sample_data_collection_link', schema='seq')
    op.drop_table('ref_seq', schema='seq')
    op.drop_table('ref_allele', schema='seq')
    op.drop_table('allele', schema='seq')
    op.drop_table('tree_algorithm_class', schema='seq')
    op.drop_table('taxon_set', schema='seq')
    op.drop_table('taxon', schema='seq')
    op.drop_table('seq_category_set', schema='seq')
    op.drop_table('sample', schema='seq')
    op.drop_table('protocol_set', schema='seq')
    op.drop_table('locus_set', schema='seq')
    op.drop_table('locus_code_map', schema='seq')
    op.drop_table('locus', schema='seq')
    op.drop_table('file', schema='file')
    op.drop_table('outage', schema='system')
    op.drop_table('organization_admin_policy', schema='abac')
    op.drop_table('user_invitation', schema='organization')
    op.drop_table('contact', schema='organization')
    op.drop_table('user', schema='organization')
    op.drop_table('site', schema='organization')
    op.drop_table('organization_set_member', schema='organization')
    op.drop_table('organization_identifier_issuer_link', schema='organization')
    op.drop_table('data_collection_set_member', schema='organization')
    op.drop_table('organization_set', schema='organization')
    op.drop_table('organization', schema='organization')
    op.drop_table('identifier_issuer', schema='organization')
    op.drop_table('data_collection_set', schema='organization')
    op.drop_table('data_collection', schema='organization')
    # ### end Alembic commands ###
