"""initial_schema

Revision ID: b9c5e10bf42c
Revises:
Create Date: 2026-08-24 11:44:08.346921
"""
from __future__ import annotations

from alembic import op
import gen_epix.fastapp.repositories.sa.util
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b9c5e10bf42c'
down_revision = None
branch_labels = None
depends_on = None


def _create_schemas() -> None:
    if op.get_bind().dialect.name == "mssql":
        for schema in ("abac", "organization", "system"):
            op.execute(
                sa.text(
                    f"IF SCHEMA_ID('{schema}') IS NULL "
                    f"EXEC('CREATE SCHEMA [{schema}]')"
                )
            )


def upgrade() -> None:
    _create_schemas()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_admin_policy',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_admin_policy_organization_id_user_id'),
    schema='abac'
    )
    op.create_table('data_collection',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_name'),
    schema='organization'
    )
    op.create_table('data_collection_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_set_name'),
    schema='organization'
    )
    op.create_table('identifier_issuer',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_identifier_issuer_code'),
    schema='organization'
    )
    op.create_table('organization',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organization_code'),
    sa.UniqueConstraint('name', name='uq_organization_name'),
    schema='organization'
    )
    op.create_table('organization_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_organization_set_name'),
    schema='organization'
    )
    op.create_table('data_collection_set_member',
    sa.Column('data_collection_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['data_collection_id'], ['organization.data_collection.id'], name='fk_data_collection_set_member_data_collection_id'),
    sa.ForeignKeyConstraint(['data_collection_set_id'], ['organization.data_collection_set.id'], name='fk_data_collection_set_member_data_collection_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_collection_set_id', 'data_collection_id', name='uq_data_collection_set_member_data_collection_set_id_data_collection_id'),
    schema='organization'
    )
    op.create_table('organization_identifier_issuer_link',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['identifier_issuer_id'], ['organization.identifier_issuer.id'], name='fk_organization_identifier_issuer_link_identifier_issuer_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_identifier_issuer_link_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'identifier_issuer_id', name='uq_organization_identifier_issuer_link_organization_id_identifier_issuer_id'),
    schema='organization'
    )
    op.create_table('organization_set_member',
    sa.Column('organization_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_set_member_organization_id'),
    sa.ForeignKeyConstraint(['organization_set_id'], ['organization.organization_set.id'], name='fk_organization_set_member_organization_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_set_id', 'organization_id', name='uq_organization_set_member_organization_set_id_organization_id'),
    schema='organization'
    )
    op.create_table('site',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_site_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_site_organization_id_name'),
    schema='organization'
    )
    op.create_table('user',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_user_key'),
    schema='organization'
    )
    op.create_table('contact',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('site_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['organization.site.id'], name='fk_contact_site_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_contact_site_id_name'),
    schema='organization'
    )
    op.create_table('user_invitation',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('invited_by_user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['organization.user.id'], name='fk_user_invitation_invited_by_user_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_invitation_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'expires_at', name='uq_user_invitation_key_expires_at'),
    schema='organization'
    )
    op.create_table('outage',
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('visible_from', sa.DateTime(), nullable=True),
    sa.Column('visible_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outage', schema='system')
    op.drop_table('user_invitation', schema='organization')
    op.drop_table('contact', schema='organization')
    op.drop_table('user', schema='organization')
    op.drop_table('site', schema='organization')
    op.drop_table('organization_set_member', schema='organization')
    op.drop_table('organization_identifier_issuer_link', schema='organization')
    op.drop_table('data_collection_set_member', schema='organization')
    op.drop_table('organization_set', schema='organization')
    op.drop_table('organization', schema='organization')
    op.drop_table('identifier_issuer', schema='organization')
    op.drop_table('data_collection_set', schema='organization')
    op.drop_table('data_collection', schema='organization')
    op.drop_table('organization_admin_policy', schema='abac')
    # ### end Alembic commands ###
