# Global configuration: least strict settings
[mypy]
python_version = 3.13
pretty = True
warn_unused_configs = True
warn_redundant_casts = True
warn_unreachable = True
strict_equality = True
strict_optional = True
check_untyped_defs = True
disallow_incomplete_defs = True
# Not strict
warn_return_any = False
warn_unused_ignores = False
disallow_untyped_calls = False
disallow_untyped_defs = False
disallow_untyped_decorators = False
ignore_missing_imports = False


# Specific configurations for different parts of the codebase with more strict settings

# Most strict settings for the most generic code
[mypy-gen_epix.fastapp.*]
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True
[mypy-gen_epix.filter.*]
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True
[mypy-gen_epix.transform.*]
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True
[mypy-gen_epix.commondb.*]
warn_return_any = True
warn_unused_ignores = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True

# Intermediate strict settings for the more specific code
[mypy-gen_epix.casedb.*]
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True
[mypy-gen_epix.seqdb.*]
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True
[mypy-gen_epix.omopdb.*]
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_untyped_decorators = True
ignore_missing_imports = True

# Least strict settings for tests
[mypy-test.*]
[mypy-tests.*]


# Missing stubs / third-party libraries
[mypy-pandas]
ignore_missing_imports = True
[mypy-yaml]
ignore_missing_imports = True