[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "Gen-EpiX"
version = "7.1.1"
authors = [
    { name="RIVM-bioinformatics", email="ids-bioinformatics@rivm.nl" },
]
description = "Genomic Epidemiology platform for disease X"
readme = "README.md"
license = "EUPL-1.2"
license-files = ["LICENSE"]
keywords = ["Genomic Epidemiology", "Disease X", "Bioinformatics"]
classifiers = [
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]==0.135.1",
    "gunicorn==25.2.*",
    "starlette==1.0.*",
    "httpx==0.28.1",
    "pyjwt==2.11.0",
    "urllib3==2.6.3",
    "sqlalchemy==2.0.48",
    "sqlalchemy_utils==0.42.1",
    "pydantic==2.12.5",
    "ulid-py==1.1.0",
    "fire==0.7.1",
    "dynaconf==3.2.13",
    "PyYAML==6.0.3",
    "scipy==1.17.1",
    "numpy==2.4.3",
    "biopython==1.86",
    "cachetools==7.0.5",
    "slowapi==0.1.9",
    "python-dateutil==2.9.0.post0",
    "types-python-dateutil==2.9.*",
    "types-setuptools==82.0.*",
    "python-multipart==0.0.22",
]

[project.urls]
Homepage = "https://github.com/RIVM-bioinformatics/gen-epix-api/"
Documentation = "https://rivm-bioinformatics.github.io/gen-epix-api/"

[tool.setuptools.packages.find]
where = ["."]
include = ["gen_epix*"]
exclude = ["tests", "tests.*", "docs", "docs.*", "data", "data.*", "cert", "cert.*", "cicd", "cicd.*"]

[tool.pytest-gremlins]
paths = ["gen_epix"]

[tool.black]
line-length = 88
target-version = ['py313']

[tool.isort]
profile = "black"
float_to_top = true
line_length = 88