[pytest]
norecursedirs =
    mutants
markers =
    scenario_ids(id): Custom marker for scenario IDs used in test reporting.
    integration: Marker for integration tests.
addopts = -v -s --import-mode=importlib
filterwarnings =
    ignore:.*shadows an attribute in parent.*
