[pytest]
norecursedirs =
    mutants
markers =
    scenario_ids(id): Custom marker for scenario IDs used in test reporting.
addopts = -v -s
filterwarnings =
    ignore:.*shadows an attribute in parent.*
