import json
from collections.abc import Iterable
from datetime import datetime
from typing import Any, ClassVar, Self
from uuid import UUID

from pydantic import Field, field_serializer, field_validator, model_validator

from gen_epix.casedb.domain import enum, exc
from gen_epix.casedb.domain.model.geo import RegionSet
from gen_epix.casedb.domain.model.ontology import ConceptSet, Disease, EtiologicalAgent
from gen_epix.commondb.domain.model import Model
from gen_epix.fastapp.domain import Entity, create_keys, create_links
from gen_epix.seqdb.domain import enum as seqdb_enum
from gen_epix.util import copy_model_field


class GeneticDistanceProtocol(Model):

    ENTITY: ClassVar = Entity(
        snake_case_plural_name="genetic_distance_protocols",
        table_name="genetic_distance_protocol",
        persistable=True,
        keys=create_keys({1: "seqdb_seq_distance_protocol_id", 2: "name"}),
    )
    seqdb_seq_distance_protocol_id: UUID = Field(
        description="The ID of the protocol in seqdb"
    )
    seqdb_seq_distance_protocol_type: seqdb_enum.SeqDistanceProtocolType = Field(
        description="The type of the genetic distance protocol in seqdb"
    )
    name: str = Field(description="The name of the protocol", max_length=255)
    description: str | None = Field(
        default=None, description="The description of the protocol", max_length=1000
    )
    seqdb_max_stored_distance: float | None = Field(
        default=None,
        description="The maximum distance that is stored in seqdb for this protocol",
    )
    seqdb_is_integer_distance: bool = Field(
        description="Whether the distances between two profiles generated by this protocol are integers in seqdb",
    )
    min_scale_unit: float = Field(description="The minimum unit to be shown in a scale")


class TreeAlgorithmClass(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="tree_algorithm_classes",
        table_name="tree_algorithm_class",
        persistable=True,
        keys=create_keys({1: "code", 2: "name"}),
    )
    code: str = Field(
        description="The code of the tree algorithm class", max_length=255
    )
    name: str = Field(
        description="The name of the tree algorithm class", max_length=255
    )
    is_seq_based: bool = Field(
        description="Whether the sequence or alignment is needed as input"
    )
    is_dist_based: bool = Field(
        description="Whether the distance between sequences is needed as input"
    )
    rank: int | None = Field(
        default=None,
        description="The rank of the tree algorithm class, if relevant.",
    )


class TreeAlgorithm(Model):
    """
    See https://en.wikipedia.org/wiki/Hierarchical_clustering,
    https://en.wikipedia.org/wiki/Neighbor_joining,
     https://en.wikipedia.org/wiki/Computational_phylogenetics,
     https://en.wikipedia.org/wiki/Spanning_tree
    """

    ENTITY: ClassVar = Entity(
        snake_case_plural_name="tree_algorithms",
        table_name="tree_algorithm",
        persistable=True,
        keys=create_keys({1: "seqdb_tree_algorithm_id", 2: "code", 3: "name"}),
        links=create_links(
            {
                1: (
                    "tree_algorithm_class_id",
                    TreeAlgorithmClass,
                    "tree_algorithm_class",
                ),
            }
        ),
    )
    tree_algorithm_class_id: UUID = Field(
        description="The ID of the tree algorithm class. FOREIGN KEY"
    )
    tree_algorithm_class: TreeAlgorithmClass | None = Field(
        default=None, description="The class of algorithm"
    )
    seqdb_tree_algorithm_id: UUID = Field(
        description="The ID of the tree algorithm in seqdb"
    )
    code: enum.TreeAlgorithmType = Field(description="The code of the tree algorithm")
    name: str = Field(description="The name of the tree algorithm", max_length=255)
    description: str | None = Field(
        default=None,
        description="The description of the tree algorithm",
        max_length=1000,
    )
    is_ultrametric: bool = Field(description="Whether the tree is ultrametric")
    rank: int | None = Field(
        default=None,
        description="The rank of the tree algorithm, if relevant.",
    )


class Dim(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="dims",
        table_name="dim",
        persistable=True,
        keys=create_keys({1: "code"}),
    )
    dim_type: enum.DimType = Field(description="The type of dimension.")
    code: str = Field(description="The code for the dimension.", max_length=255)
    label: str = Field(description="The label for the dimension.")
    rank: int = Field(
        default=0,
        description="The rank of the dimension, for (partial) ordering.",
    )
    col_code_prefix: str | None = Field(
        default=None,
        description=(
            "The column code prefix used to compose a full column code,"
            " if different from the code field."
        ),
    )
    description: str | None = Field(
        default=None, description="Description of the dimension.", max_length=1000
    )
    props: dict[str, Any] = Field(
        default_factory=dict, description="Additional properties of the dimension."
    )

    @field_validator("code", mode="before")
    @classmethod
    def validate_code(cls, value: Any) -> str:
        return str(value)


class Col(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="cols",
        table_name="col",
        persistable=True,
        keys=create_keys({1: ("dim_id", "code")}),
        links=create_links(
            {
                1: ("dim_id", Dim, "dim"),
                2: ("concept_set_id", ConceptSet, "concept_set"),
                3: ("region_set_id", RegionSet, "region_set"),
                4: (
                    "genetic_distance_protocol_id",
                    GeneticDistanceProtocol,
                    "genetic_distance_protocol",
                ),
            }
        ),
    )
    dim_id: UUID = Field(description="The ID of the dimension. FOREIGN KEY")
    dim: Dim | None = Field(default=None, description="The dimension")
    code_suffix: str | None = Field(
        default=None,
        description=(
            "The code suffix for the column used to compose a full column code,"
            " if needed in addition to the dimension column code prefix. See code field."
        ),
    )
    code: str = Field(
        description=(
            "The code for the column, "
            "equal to the dimension column code prefix dot code_suffix"
            " (dot code_suffix only if the latter is not null)."
        ),
        max_length=255,
    )
    rank: int = Field(
        default=0,
        description="The rank of the column within the dimension, for (partial) ordering.",
    )
    label: str | None = Field(
        default=None,
        description="The label for the column, if different from the code.",
    )
    col_type: enum.ColType = Field(
        description="The type of the data stored in the column."
    )
    concept_set_id: UUID | None = Field(
        default=None,
        description=(
            "The ID of the concept set for the column in case of type"
            " NOMINAL, ORDINAL, INTERVAL. FOREIGN KEY"
        ),
    )
    concept_set: ConceptSet | None = Field(default=None, description="The concept set.")
    region_set_id: UUID | None = Field(
        default=None,
        description="The ID of the region set for the column in case of type GEO. FOREIGN KEY",
    )
    region_set: RegionSet | None = Field(default=None, description="The region set.")
    genetic_distance_protocol_id: UUID | None = Field(
        default=None,
        description=(
            "The ID of the genetic distance protocol"
            " that produces the input for the tree algorithm. FOREIGN KEY"
        ),
    )
    genetic_distance_protocol: GeneticDistanceProtocol | None = Field(
        default=None, description="The genetic distance protocol"
    )
    description: str | None = Field(
        default=None, description="Description of the column.", max_length=1000
    )
    props: dict[str, Any] = Field(
        default_factory=dict, description="Additional properties of the column."
    )

    @field_validator("code", mode="before")
    @classmethod
    def validate_code(cls, value: Any) -> str:
        return str(value)

    @model_validator(mode="after")
    def _validate_state(self) -> Self:
        if self.col_type in enum.ColTypeSet.HAS_CONCEPT_SET.value:
            if self.concept_set_id is None:
                raise exc.InvalidArgumentsError(
                    f"No concept_set_id provided for col_type {self.col_type.value}"
                )
        if self.col_type in enum.ColTypeSet.HAS_REGION_SET.value:
            if self.region_set_id is None:
                raise exc.InvalidArgumentsError(
                    f"No region_set_id provided for col_type {self.col_type.value}"
                )
        if self.col_type in enum.ColTypeSet.HAS_GENETIC_DISTANCE_PROTOCOL.value:
            if self.genetic_distance_protocol_id is None:
                raise exc.InvalidArgumentsError(
                    f"No genetic_distance_protocol_id provided for col_type {self.col_type.value}"
                )
        return self


class CaseType(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_types",
        table_name="case_type",
        persistable=True,
        keys=create_keys({1: "name"}),
        links=create_links(
            {
                1: ("disease_id", Disease, "disease"),
                2: ("etiological_agent_id", EtiologicalAgent, "etiological_agent"),
            }
        ),
    )
    name: str = Field(description="The name of the case type", max_length=255)
    description: str | None = Field(
        default=None, description="The description of the case type", max_length=1000
    )
    disease_id: UUID | None = Field(
        default=None, description="The ID of the disease. FOREIGN KEY"
    )
    disease: Disease | None = Field(default=None, description="The disease")
    etiological_agent_id: UUID | None = Field(
        default=None, description="The ID of the etiological agent. FOREIGN KEY"
    )
    etiological_agent: EtiologicalAgent | None = Field(
        default=None, description="The etiological agent"
    )
    create_max_n_cases: int = Field(
        ge=0,
        default=0,
        description=(
            "Maximum number of cases that can be created in one batch, if the user's rights are constrained by this setting. If 0, no restriction is applied."
        ),
    )
    read_max_n_cases: int = Field(
        ge=0,
        default=0,
        description=(
            "Maximum number of cases that can be read in one batch, if the user's rights are constrained by this setting. If 0, no restriction is applied."
        ),
    )
    read_max_tree_size: int = Field(
        ge=0,
        default=0,
        description=(
            "Maximum number of cases for which a tree may be calculated, if the user's rights are constrained by this setting. If 0, no restriction is applied."
        ),
    )
    update_max_n_cases: int = Field(
        ge=0,
        default=0,
        description=(
            "Maximum number of cases that can be updated in one batch, if the user's rights are constrained by this setting. If 0, no restriction is applied."
        ),
    )
    delete_max_n_cases: int = Field(
        ge=0,
        default=0,
        description=(
            "Maximum number of cases that can be deleted in one batch, if the user's rights are constrained by this setting. If 0, no restriction is applied."
        ),
    )


class CaseTypeSetCategory(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_set_categories",
        table_name="case_type_set_category",
        persistable=True,
        keys=create_keys({1: "name"}),
    )
    name: str = Field(
        description="The name of the case type set category", max_length=255
    )
    description: str | None = Field(
        default=None,
        description="The description of the case type set category",
        max_length=1000,
    )
    rank: int = Field(description="The rank of the case type set category")
    purpose: enum.CaseTypeSetCategoryPurpose = Field(
        default=enum.CaseTypeSetCategoryPurpose.CONTENT,
        description="The purpose of the case type set category",
    )

    @field_serializer("purpose", mode="plain")
    def _serialize_purpose(self, value: enum.CaseTypeSetCategoryPurpose) -> str:
        return value.value


class CaseTypeDim(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_dims",
        table_name="case_type_dim",
        persistable=True,
        keys=create_keys({1: ("case_type_id", "dim_id", "occurrence")}),
        links=create_links(
            {
                1: ("case_type_id", CaseType, "case_type"),
                2: ("dim_id", Dim, "dim"),
            }
        ),
    )
    case_type_id: UUID = Field(description="The ID of the case type. FOREIGN KEY")
    case_type: CaseType | None = Field(default=None, description="The case type")
    dim_id: UUID = Field(description="The ID of the dimension. FOREIGN KEY")
    dim: Dim | None = Field(default=None, description="The dimension")
    occurrence: int = Field(
        default=0,
        description=(
            "The index of the occurrence of the dimension for this case type. "
            "E.g. for first and second vaccination time it would be 1 and 2. "
            "Zero if only a single occurrence is expected or created."
        ),
        ge=0,
    )
    code: str = Field(
        description=(
            "The code for the case type dimension, "
            "equal to the dimension code and, if present, dot 'x' occurrence. "
            "E.g. 'Host.Vaccination.Date.COVID19.x1' for occurrence=1, "
            "'Specimen.Sampling.Date' for occurrence=0"
        ),
        max_length=255,
    )
    label: str | None = Field(
        default=None,
        description=(
            "The label of the dimension for this case type,"
            " if different from the general dimension label."
        ),
        max_length=255,
    )
    description: str | None = Field(
        default=None,
        description="Description of the case type dimension.",
        max_length=1000,
    )
    rank: int = Field(
        description="The rank of the case type dimension within the case type for (partial) ordering."
    )
    is_case_date_dim: bool = Field(
        default=False,
        description="Indicates if this dimension is to be used to derive the case date.",
    )


class CaseTypeCol(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_cols",
        table_name="case_type_col",
        persistable=True,
        keys=create_keys({1: ("case_type_dim_id", "col_id")}),
        links=create_links(
            {
                1: ("case_type_id", CaseType, "case_type"),
                2: ("case_type_dim_id", CaseTypeDim, "case_type_dim"),
                3: ("col_id", Col, "col"),
            }
        ),
    )
    case_type_id: UUID = copy_model_field(CaseTypeDim, "case_type_id")
    case_type: CaseType | None = copy_model_field(CaseTypeDim, "case_type")
    case_type_dim_id: UUID = Field(
        description="The ID of the case type dimension. FOREIGN KEY"
    )
    case_type_dim: CaseTypeDim | None = Field(
        default=None, description="The case type dimension"
    )
    col_id: UUID = Field(description="The ID of the column. FOREIGN KEY")
    col: Col | None = Field(default=None, description="The column")
    code: str = Field(
        description=(
            "The code for the case type column, "
            "equal to the column code and, if present, dot 'x' occurrence. "
            "E.g. 'Host.Vaccination.Date.COVID19.x1' for occurrence=1, "
            "'Specimen.Sampling.Date' for occurrence=0"
        ),
        max_length=255,
    )
    rank: int = Field(
        description=(
            "The rank of the column within the case type dim for (partial) ordering, "
            "if different from the general dimension and column rank."
        ),
    )
    label: str | None = Field(
        default=None,
        description=(
            "The label of the column for this case type,"
            " if different from the general column label."
        ),
        max_length=255,
    )
    description: str | None = Field(
        default=None,
        description="Description of the case type column.",
        max_length=1000,
    )
    min_value: float | None = Field(
        default=None, description="The minimum value for a numeric column"
    )
    max_value: float | None = Field(
        default=None, description="The maximum value for a numeric column"
    )
    min_datetime: datetime | None = Field(
        default=None, description="The minimum datetime for a time column"
    )
    max_datetime: datetime | None = Field(
        default=None, description="The maximum datetime for a time column"
    )
    min_length: int | None = Field(
        default=None, description="The minimum length for a text column, if not empty"
    )
    max_length: int | None = Field(
        default=None, description="The maximum length for a text column, if not empty"
    )
    pattern: str | None = Field(
        default=None,
        description="The regular expression for a text column, if not empty",
    )
    ncbi_taxid: str | None = Field(
        default=None,
        description=(
            "The NCBI taxid for the column, if the column is a genetic sequence"
        ),
        pattern=r"^NCBI:txid\d+$",
    )
    genetic_sequence_case_type_col_id: UUID | None = Field(
        default=None,
        description=(
            "The ID of the genetic sequence case type column, "
            "if this is a genetic sequence column. FOREIGN KEY"
        ),
    )
    tree_algorithm_codes: set[enum.TreeAlgorithmType] | None = Field(
        default=None,
        description=(
            "The set of tree algorithms that can be used for the case type column"
        ),
    )
    props: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional properties of the case type column.",
    )

    @field_validator("code", mode="before")
    @classmethod
    def validate_code(cls, value: Any) -> str:
        return str(value)

    @field_validator("tree_algorithm_codes", mode="before")
    @classmethod
    def validate_tree_algorithm_codes(
        cls, value: Iterable[enum.TreeAlgorithmType] | str | None
    ) -> set[enum.TreeAlgorithmType] | None:
        if value is None or isinstance(value, set):
            return value
        if isinstance(value, str):
            return {enum.TreeAlgorithmType[x] for x in json.loads(value)}
        return set(value)

    @field_serializer("tree_algorithm_codes", mode="plain")
    def _serialize_tree_algorithm_codes(
        self, value: list[enum.TreeAlgorithmType] | None
    ) -> list[str] | None:
        return None if value is None else [x.value for x in value]


class CaseTypeColSet(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_col_sets",
        table_name="case_type_col_set",
        persistable=True,
        keys=create_keys({1: "name"}),
    )
    name: str = Field(
        description="The name of a case type column set, UNIQUE", max_length=255
    )
    description: str | None = Field(
        default=None,
        description="The description of the case type column set",
        max_length=1000,
    )


class CaseTypeColSetMember(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_col_set_members",
        table_name="case_type_col_set_member",
        persistable=True,
        keys=create_keys({1: ("case_type_col_set_id", "case_type_col_id")}),
        links=create_links(
            {
                1: ("case_type_col_set_id", CaseTypeColSet, "case_type_col_set"),
                2: ("case_type_col_id", CaseTypeCol, "case_type_col"),
            }
        ),
    )
    case_type_col_set_id: UUID = Field(
        description="The ID of the case type column set. FOREIGN KEY"
    )
    case_type_col_set: CaseTypeColSet | None = Field(
        default=None, description="The case type column set"
    )
    case_type_col_id: UUID = Field(
        description="The ID of the case type column. FOREIGN KEY"
    )
    case_type_col: CaseTypeCol | None = Field(
        default=None, description="The case type column"
    )


class CaseSetCategory(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_set_categories",
        table_name="case_set_category",
        persistable=True,
        keys=create_keys({1: "name"}),
    )
    name: str = Field(
        description="The name of the case set category, UNIQUE", max_length=255
    )
    description: str | None = Field(
        description="The description of the case set category", max_length=1000
    )


class CaseSetStatus(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_set_statuses",
        table_name="case_set_status",
        persistable=True,
        keys=create_keys({1: "name"}),
    )
    name: str = Field(
        description="The name of the case set status, UNIQUE", max_length=255
    )
    description: str | None = Field(
        description="The description of the case set status", max_length=1000
    )


class CaseTypeSet(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_sets",
        table_name="case_type_set",
        persistable=True,
        keys=create_keys({1: ("case_type_set_category_id", "name")}),
        links=create_links(
            {
                1: (
                    "case_type_set_category_id",
                    CaseTypeSetCategory,
                    "case_type_set_category",
                )
            }
        ),
    )
    name: str = Field(description="The name of the case type set", max_length=255)
    description: str | None = Field(
        default=None,
        description="The description of the case type set",
        max_length=1000,
    )
    case_type_set_category_id: UUID = Field(
        description="The id of the category of the case type set. FOREIGN KEY"
    )
    case_type_set_category: CaseTypeSetCategory | None = Field(
        default=None, description="The category of the case type set"
    )
    rank: float = Field(
        description="The rank of the case type set, establishing a partial order"
    )


class CaseTypeSetMember(Model):
    ENTITY: ClassVar = Entity(
        snake_case_plural_name="case_type_set_members",
        table_name="case_type_set_member",
        persistable=True,
        keys=create_keys({1: ("case_type_set_id", "case_type_id")}),
        links=create_links(
            {
                1: ("case_type_set_id", CaseTypeSet, "case_type_set"),
                2: ("case_type_id", CaseType, "case_type"),
            }
        ),
    )
    case_type_set_id: UUID = Field(
        description="The ID of the case type set. FOREIGN KEY"
    )
    case_type_set: CaseTypeSet | None = Field(
        default=None, description="The case type set"
    )
    case_type_id: UUID = copy_model_field(CaseTypeDim, "case_type_id")
    case_type: CaseType | None = copy_model_field(CaseTypeDim, "case_type")
