[service.auth.props.automatic_new_user]
roles = ["CASEDB_ORG_USER"]

[service.auth.props.automatic_new_user.organization]
id = "018d074d-e9fc-b282-fcaa-377a752b95e5"
name = "DUMMY"

[service.auth.props.root.organization]
id = "018d074d-ea0c-e942-07db-a3cc0ba1d653"
name = "DUMMY"
legal_entity_code = "DUMMY"

[service.auth.props.root.user]
id = "019542cc-8225-8f5d-fa30-d9c3f2629703"
key = "root@dummy.org"

# TODO: remove if not used
[service.auth.props.casedb.user]
id = "019542cc-8225-8f5d-fa30-d9c3f2629703"
key = "root@dummy.org"
organization_id = "018d074d-ea0c-e942-07db-a3cc0ba1d653"
roles = ["CASEDB_APP_ADMIN"]

[service.seqdb.props]
seqdb_app_type = "LOCAL"

[service.seqdb.props.seqdb_local_app.user]
id = "018bcd02-eb19-fb14-c520-64cbb78d9135"
key = "root@dummy.org"
organization_id = "018d074d-ea0c-e942-07db-a3cc0ba1d653"
roles = ["SEQDB_APP_ADMIN"]

[service.seqdb.props.seqdb_remote_app]
module = "gen_epix.casedb.services"
class_name = "SeqdbRemoteApp"
host = "localhost"
port = "8001"
auth_protocol = "OAUTH2"
oauth_flow = "CLIENT_CREDENTIALS"
oauth_client_id = "CASEDB_FOR_SEQDB_DUMMY_CLIENT_ID"
oauth_client_secret = "CASEDB_FOR_SEQDB_DUMMY_CLIENT_SECRET"
oauth_scope = "DUMMY_SCOPE"
oauth_discovery_url = "https://your-idp.com/.well-known/openid-configuration"
