[repository.defaults]
type = "SA_SQLITE"

[repository.defaults.props]
dir="./data/casedb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.abac.empty.sqlite"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.organization.empty.sqlite"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.system.empty.sqlite"

[repository.case.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.case.empty.sqlite"

[repository.geo.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.geo.empty.sqlite"

[repository.ontology.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.ontology.empty.sqlite"

[repository.seqdb.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.seqdb.empty.sqlite"

[repository.subject.props]
file = "@format {this.repository.defaults.props.dir}/casedb.sa_sqlite.subject.empty.sqlite"
