[repository.defaults]
type = "DICT"

[repository.defaults.props]
dir="./data/casedb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.abac.empty.pkl.gz"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.organization.empty.pkl.gz"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.system.empty.pkl.gz"

[repository.case.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.case.empty.pkl.gz"

[repository.geo.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.geo.empty.pkl.gz"

[repository.ontology.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.ontology.empty.pkl.gz"

[repository.subject.props]
file = "@format {this.repository.defaults.props.dir}/casedb.dict.subject.empty.pkl.gz"
