"""refactored-case-date-to-timed-at

Revision ID: 31d021dcf0ae
Revises: 33287eafdd16
Create Date: 2026-09-08 11:56:52.535064
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31d021dcf0ae"
down_revision = "33287eafdd16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "case", sa.Column("timed_at", sa.DateTime(), nullable=True), schema="case"
    )
    op.drop_column("case", "case_date", schema="case")
    op.alter_column(
        "case_set",
        "description",
        existing_type=sa.VARCHAR(length=8000, collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.UnicodeText(),
        existing_nullable=False,
        schema="case",
    )
    op.alter_column(
        "contact",
        "phone",
        existing_type=sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
        type_=sa.Unicode(length=20),
        existing_nullable=True,
        schema="organization",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact",
        "phone",
        existing_type=sa.Unicode(length=20),
        type_=sa.VARCHAR(collation="SQL_Latin1_General_CP1_CI_AS"),
        existing_nullable=True,
        schema="organization",
    )
    op.alter_column(
        "case_set",
        "description",
        existing_type=sa.UnicodeText(),
        type_=sa.VARCHAR(length=8000, collation="SQL_Latin1_General_CP1_CI_AS"),
        existing_nullable=False,
        schema="case",
    )
    op.add_column(
        "case",
        sa.Column("case_date", sa.DATETIME(), autoincrement=False, nullable=True),
        schema="case",
    )
    op.drop_column("case", "timed_at", schema="case")
    # ### end Alembic commands ###
