"""initial_schema

Revision ID: bbc386e12a58
Revises:
Create Date: 2026-08-24 11:44:19.812833
"""
from __future__ import annotations

from alembic import op
import gen_epix.fastapp.repositories.sa.util
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'bbc386e12a58'
down_revision = None
branch_labels = None
depends_on = None


def _create_schemas() -> None:
    if op.get_bind().dialect.name == "mssql":
        for schema in ("abac", "organization", "system", "geo", "ontology", "case"):
            op.execute(
                sa.text(
                    f"IF SCHEMA_ID('{schema}') IS NULL "
                    f"EXEC('CREATE SCHEMA [{schema}]')"
                )
            )


def upgrade() -> None:
    _create_schemas()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_access_case_policy',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_type_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('add_case', sa.Boolean(), nullable=False),
    sa.Column('remove_case', sa.Boolean(), nullable=False),
    sa.Column('add_case_set', sa.Boolean(), nullable=False),
    sa.Column('remove_case_set', sa.Boolean(), nullable=False),
    sa.Column('read_col_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('write_col_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('read_case_set', sa.Boolean(), nullable=False),
    sa.Column('write_case_set', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'data_collection_id', name='uq_organization_access_case_policy_organization_id_data_collection_id'),
    schema='abac'
    )
    op.create_table('organization_share_case_policy',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_type_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('from_data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('add_case', sa.Boolean(), nullable=False),
    sa.Column('remove_case', sa.Boolean(), nullable=False),
    sa.Column('add_case_set', sa.Boolean(), nullable=False),
    sa.Column('remove_case_set', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'data_collection_id', 'from_data_collection_id', name='uq_organization_share_case_policy_organization_id_data_collection_id_from_data_collection_id'),
    schema='abac'
    )
    op.create_table('user_access_case_policy',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_type_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('add_case', sa.Boolean(), nullable=False),
    sa.Column('remove_case', sa.Boolean(), nullable=False),
    sa.Column('add_case_set', sa.Boolean(), nullable=False),
    sa.Column('remove_case_set', sa.Boolean(), nullable=False),
    sa.Column('read_col_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('write_col_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('read_case_set', sa.Boolean(), nullable=False),
    sa.Column('write_case_set', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_collection_id', name='uq_user_access_case_policy_user_id_data_collection_id'),
    schema='abac'
    )
    op.create_table('user_share_case_policy',
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_type_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('from_data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('add_case', sa.Boolean(), nullable=False),
    sa.Column('remove_case', sa.Boolean(), nullable=False),
    sa.Column('add_case_set', sa.Boolean(), nullable=False),
    sa.Column('remove_case_set', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'data_collection_id', 'from_data_collection_id', name='uq_user_share_case_policy_user_id_data_collection_id_from_data_collection_id'),
    schema='abac'
    )
    op.create_table('case_set_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_case_set_category_name'),
    schema='case'
    )
    op.create_table('case_set_status',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_case_set_status_name'),
    schema='case'
    )
    op.create_table('case_type',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('disease_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('etiological_agent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_case_type_name'),
    schema='case'
    )
    op.create_table('case_type_set_category',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('CONTENT', 'SECURITY', name='casetypesetcategorypurpose'), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_case_type_set_category_name'),
    schema='case'
    )
    op.create_table('col_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_col_set_name'),
    schema='case'
    )
    op.create_table('genetic_distance_protocol',
    sa.Column('seqdb_seq_distance_protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seqdb_seq_distance_type', sa.Enum('SNP_HAMMING', 'ALLELE_HAMMING', 'MLVA_HAMMING', 'MLVA_EUCLIDEAN', 'KMER_EUCLIDEAN', name='seqdistancetype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('seqdb_max_stored_distance', sa.Float(), nullable=True),
    sa.Column('seqdb_is_integer_distance', sa.Boolean(), nullable=False),
    sa.Column('min_scale_unit', sa.Float(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_genetic_distance_protocol_name'),
    sa.UniqueConstraint('seqdb_seq_distance_protocol_id', name='uq_genetic_distance_protocol_seqdb_seq_distance_protocol_id'),
    schema='case'
    )
    op.create_table('ref_dim',
    sa.Column('dim_type', sa.Enum('TEXT', 'IDENTIFIER', 'NUMBER', 'TIME', 'GEO', 'ORGANIZATION', 'OTHER', name='dimtype'), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('col_code_prefix', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_ref_dim_code'),
    schema='case'
    )
    op.create_table('tree_algorithm_class',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_seq_based', sa.Boolean(), nullable=False),
    sa.Column('is_dist_based', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tree_algorithm_class_code'),
    sa.UniqueConstraint('name', name='uq_tree_algorithm_class_name'),
    schema='case'
    )
    op.create_table('case',
    sa.Column('case_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_in_data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('cohort', sa.JSON(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('case_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case.case_type.id'], name='fk_case_case_type_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='case'
    )
    op.create_table('case_set',
    sa.Column('case_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_in_data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=8000), nullable=False),
    sa.Column('case_set_date', sa.DateTime(), nullable=True),
    sa.Column('case_set_category_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_set_status_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_set_category_id'], ['case.case_set_category.id'], name='fk_case_set_case_set_category_id'),
    sa.ForeignKeyConstraint(['case_set_status_id'], ['case.case_set_status.id'], name='fk_case_set_case_set_status_id'),
    sa.ForeignKeyConstraint(['case_type_id'], ['case.case_type.id'], name='fk_case_set_case_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_case_set_code'),
    sa.UniqueConstraint('name', name='uq_case_set_name'),
    schema='case'
    )
    op.create_table('case_type_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('case_type_set_category_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('rank', sa.Float(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_set_category_id'], ['case.case_type_set_category.id'], name='fk_case_type_set_case_type_set_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type_set_category_id', 'name', name='uq_case_type_set_case_type_set_category_id_name'),
    schema='case'
    )
    op.create_table('dim',
    sa.Column('case_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('ref_dim_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('occurrence', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_case_date_dim', sa.Boolean(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case.case_type.id'], name='fk_dim_case_type_id'),
    sa.ForeignKeyConstraint(['ref_dim_id'], ['case.ref_dim.id'], name='fk_dim_ref_dim_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type_id', 'ref_dim_id', 'occurrence', name='uq_dim_case_type_id_ref_dim_id_occurrence'),
    schema='case'
    )
    op.create_table('ref_col',
    sa.Column('ref_dim_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code_suffix', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('col_type', sa.Enum('TEXT', 'CONTEXT_FREE_GRAMMAR_JSON', 'CONTEXT_FREE_GRAMMAR_XML', 'REGULAR_LANGUAGE', 'NOMINAL', 'ORDINAL', 'INTERVAL', 'TIME_DAY', 'TIME_WEEK', 'TIME_MONTH', 'TIME_QUARTER', 'TIME_YEAR', 'GEO_LATLON', 'GEO_REGION', 'ID_PERSON', 'ID_CASE', 'ID_SAMPLE', 'ID_EVENT', 'ID_GENETIC_SEQUENCE', 'DECIMAL_0', 'DECIMAL_1', 'DECIMAL_2', 'DECIMAL_3', 'DECIMAL_4', 'DECIMAL_5', 'DECIMAL_6', 'GENETIC_READS', 'GENETIC_SEQUENCE', 'GENETIC_PROFILE', 'GENETIC_DISTANCE', 'ORGANIZATION', 'OTHER', name='coltype'), nullable=False),
    sa.Column('concept_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('region_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('genetic_distance_protocol_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('regex', sa.Text(), nullable=True),
    sa.Column('schema_definition', sa.Text(), nullable=True),
    sa.Column('schema_uri', sa.Text(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['genetic_distance_protocol_id'], ['case.genetic_distance_protocol.id'], name='fk_ref_col_genetic_distance_protocol_id'),
    sa.ForeignKeyConstraint(['ref_dim_id'], ['case.ref_dim.id'], name='fk_ref_col_ref_dim_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_dim_id', 'code', name='uq_ref_col_ref_dim_id_code'),
    schema='case'
    )
    op.create_table('tree_algorithm',
    sa.Column('tree_algorithm_class_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('seqdb_tree_algorithm_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code', sa.Enum('SLINK', 'CLINK', 'UPGMA', 'WPGMA', 'UPGMC', 'WPGMC', 'VERSATILE', 'MISSQ', 'MNSSQ', 'MIVAR', 'MNVAR', 'MINI_MAX', 'HAUSDORFF', 'MIN_SUM_MEDOID', 'MIN_SUM_INCREASE_MEDOID', 'MEDOID', 'MIN_ENERGY', 'FITCH_MARGOLIASH', 'MAX_PARSIMONY', 'ML', 'BAYESIAN_INFERENCE', 'MIN_SPANNING', 'NJ', name='treealgorithmtype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_ultrametric', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['tree_algorithm_class_id'], ['case.tree_algorithm_class.id'], name='fk_tree_algorithm_tree_algorithm_class_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tree_algorithm_code'),
    sa.UniqueConstraint('name', name='uq_tree_algorithm_name'),
    sa.UniqueConstraint('seqdb_tree_algorithm_id', name='uq_tree_algorithm_seqdb_tree_algorithm_id'),
    schema='case'
    )
    op.create_table('case_data_collection_link',
    sa.Column('case_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.case.id'], name='fk_case_data_collection_link_case_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'data_collection_id', name='uq_case_data_collection_link_case_id_data_collection_id'),
    schema='case'
    )
    op.create_table('case_identifier',
    sa.Column('internal_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['internal_id'], ['case.case.id'], name='fk_case_identifier_internal_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_issuer_id', 'external_id', name='uq_case_identifier_identifier_issuer_id_external_id'),
    schema='case'
    )
    op.create_table('case_set_data_collection_link',
    sa.Column('case_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_set_id'], ['case.case_set.id'], name='fk_case_set_data_collection_link_case_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_set_id', 'data_collection_id', name='uq_case_set_data_collection_link_case_set_id_data_collection_id'),
    schema='case'
    )
    op.create_table('case_set_member',
    sa.Column('case_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('classification', sa.Enum('POSSIBLE', 'PROBABLE', 'CONFIRMED', name='caseclassification'), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['case.case.id'], name='fk_case_set_member_case_id'),
    sa.ForeignKeyConstraint(['case_set_id'], ['case.case_set.id'], name='fk_case_set_member_case_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_set_id', 'case_id', name='uq_case_set_member_case_set_id_case_id'),
    schema='case'
    )
    op.create_table('case_type_set_member',
    sa.Column('case_type_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('case_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case.case_type.id'], name='fk_case_type_set_member_case_type_id'),
    sa.ForeignKeyConstraint(['case_type_set_id'], ['case.case_type_set.id'], name='fk_case_type_set_member_case_type_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type_set_id', 'case_type_id', name='uq_case_type_set_member_case_type_set_id_case_type_id'),
    schema='case'
    )
    op.create_table('col',
    sa.Column('case_type_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('dim_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('ref_col_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('min_datetime', sa.DateTime(), nullable=True),
    sa.Column('max_datetime', sa.DateTime(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=True),
    sa.Column('ncbi_taxid', sa.Text(), nullable=True),
    sa.Column('genetic_sequence_col_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('tree_algorithm_codes', sa.JSON(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['case_type_id'], ['case.case_type.id'], name='fk_col_case_type_id'),
    sa.ForeignKeyConstraint(['dim_id'], ['case.dim.id'], name='fk_col_dim_id'),
    sa.ForeignKeyConstraint(['ref_col_id'], ['case.ref_col.id'], name='fk_col_ref_col_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dim_id', 'ref_col_id', name='uq_col_dim_id_ref_col_id'),
    schema='case'
    )
    op.create_table('col_set_member',
    sa.Column('col_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('col_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['col_id'], ['case.col.id'], name='fk_col_set_member_col_id'),
    sa.ForeignKeyConstraint(['col_set_id'], ['case.col_set.id'], name='fk_col_set_member_col_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('col_set_id', 'col_id', name='uq_col_set_member_col_set_id_col_id'),
    schema='case'
    )
    op.create_table('region_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region_code_as_label', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.Float(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_region_set_code'),
    sa.UniqueConstraint('name', name='uq_region_set_name'),
    schema='geo'
    )
    op.create_table('region',
    sa.Column('region_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['region_set_id'], ['geo.region_set.id'], name='fk_region_region_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_set_id', 'code', name='uq_region_region_set_id_code'),
    schema='geo'
    )
    op.create_table('region_set_shape',
    sa.Column('region_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('geo_json', sa.Text(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['region_set_id'], ['geo.region_set.id'], name='fk_region_set_shape_region_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_set_id', 'scale', name='uq_region_set_shape_region_set_id_scale'),
    schema='geo'
    )
    op.create_table('region_relation',
    sa.Column('from_region_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('to_region_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('relation', sa.Enum('IS_SEPARATE_FROM', 'IS_ADJACENT_TO', 'OVERLAPS_WITH', 'CONTAINS', name='regionrelationtype'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['from_region_id'], ['geo.region.id'], name='fk_region_relation_from_region_id'),
    sa.ForeignKeyConstraint(['to_region_id'], ['geo.region.id'], name='fk_region_relation_to_region_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_region_id', 'to_region_id', name='uq_region_relation_from_region_id_to_region_id'),
    schema='geo'
    )
    op.create_table('concept_set',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('CONTEXT_FREE_GRAMMAR_JSON', 'CONTEXT_FREE_GRAMMAR_XML', 'REGULAR_LANGUAGE', 'NOMINAL', 'ORDINAL', 'INTERVAL', name='conceptsettype'), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_concept_set_name'),
    schema='ontology'
    )
    op.create_table('disease',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icd_code', sa.String(length=255), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_disease_name'),
    schema='ontology'
    )
    op.create_table('etiological_agent',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_etiological_agent_name'),
    schema='ontology'
    )
    op.create_table('concept',
    sa.Column('concept_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['concept_set_id'], ['ontology.concept_set.id'], name='fk_concept_concept_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_set_id', 'code', name='uq_concept_concept_set_id_code'),
    schema='ontology'
    )
    op.create_table('etiology',
    sa.Column('disease_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('etiological_agent_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['ontology.disease.id'], name='fk_etiology_disease_id'),
    sa.ForeignKeyConstraint(['etiological_agent_id'], ['ontology.etiological_agent.id'], name='fk_etiology_etiological_agent_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_id', 'etiological_agent_id', name='uq_etiology_disease_id_etiological_agent_id'),
    schema='ontology'
    )
    op.create_table('concept_relation',
    sa.Column('from_concept_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('to_concept_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('relation', sa.Enum('CONTAINS', name='conceptrelationtype'), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['from_concept_id'], ['ontology.concept.id'], name='fk_concept_relation_from_concept_id'),
    sa.ForeignKeyConstraint(['to_concept_id'], ['ontology.concept.id'], name='fk_concept_relation_to_concept_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_concept_id', 'to_concept_id', name='uq_concept_relation_from_concept_id_to_concept_id'),
    schema='ontology'
    )
    op.create_table('data_collection',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_name'),
    schema='organization'
    )
    op.create_table('data_collection_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_data_collection_set_name'),
    schema='organization'
    )
    op.create_table('identifier_issuer',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_identifier_issuer_code'),
    schema='organization'
    )
    op.create_table('organization',
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organization_code'),
    sa.UniqueConstraint('name', name='uq_organization_name'),
    schema='organization'
    )
    op.create_table('organization_set',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_organization_set_name'),
    schema='organization'
    )
    op.create_table('data_collection_set_member',
    sa.Column('data_collection_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('data_collection_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['data_collection_id'], ['organization.data_collection.id'], name='fk_data_collection_set_member_data_collection_id'),
    sa.ForeignKeyConstraint(['data_collection_set_id'], ['organization.data_collection_set.id'], name='fk_data_collection_set_member_data_collection_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_collection_set_id', 'data_collection_id', name='uq_data_collection_set_member_data_collection_set_id_data_collection_id'),
    schema='organization'
    )
    op.create_table('organization_identifier_issuer_link',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('identifier_issuer_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['identifier_issuer_id'], ['organization.identifier_issuer.id'], name='fk_organization_identifier_issuer_link_identifier_issuer_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_identifier_issuer_link_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'identifier_issuer_id', name='uq_organization_identifier_issuer_link_organization_id_identifier_issuer_id'),
    schema='organization'
    )
    op.create_table('organization_set_member',
    sa.Column('organization_set_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_organization_set_member_organization_id'),
    sa.ForeignKeyConstraint(['organization_set_id'], ['organization.organization_set.id'], name='fk_organization_set_member_organization_set_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_set_id', 'organization_id', name='uq_organization_set_member_organization_set_id_organization_id'),
    schema='organization'
    )
    op.create_table('site',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_site_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_site_organization_id_name'),
    schema='organization'
    )
    op.create_table('user',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_user_key'),
    schema='organization'
    )
    op.create_table('contact',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('site_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['organization.site.id'], name='fk_contact_site_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_contact_site_id_name'),
    schema='organization'
    )
    op.create_table('user_invitation',
    sa.Column('key', sa.String(length=320), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('invited_by_user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['organization.user.id'], name='fk_user_invitation_invited_by_user_id'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization.id'], name='fk_user_invitation_organization_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'expires_at', name='uq_user_invitation_key_expires_at'),
    schema='organization'
    )
    op.create_table('organization_admin_policy',
    sa.Column('organization_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_admin_policy_organization_id_user_id'),
    schema='abac'
    )
    op.create_table('outage',
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('active_from', sa.DateTime(), nullable=True),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.Column('visible_from', sa.DateTime(), nullable=True),
    sa.Column('visible_to', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('created_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_at', gen_epix.fastapp.repositories.sa.util.UTCDateTime(), server_default=sa.text('GETUTCDATE()'), nullable=False),
    sa.Column('modified_by', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='system'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outage', schema='system')
    op.drop_table('organization_admin_policy', schema='abac')
    op.drop_table('user_invitation', schema='organization')
    op.drop_table('contact', schema='organization')
    op.drop_table('user', schema='organization')
    op.drop_table('site', schema='organization')
    op.drop_table('organization_set_member', schema='organization')
    op.drop_table('organization_identifier_issuer_link', schema='organization')
    op.drop_table('data_collection_set_member', schema='organization')
    op.drop_table('organization_set', schema='organization')
    op.drop_table('organization', schema='organization')
    op.drop_table('identifier_issuer', schema='organization')
    op.drop_table('data_collection_set', schema='organization')
    op.drop_table('data_collection', schema='organization')
    op.drop_table('concept_relation', schema='ontology')
    op.drop_table('etiology', schema='ontology')
    op.drop_table('concept', schema='ontology')
    op.drop_table('etiological_agent', schema='ontology')
    op.drop_table('disease', schema='ontology')
    op.drop_table('concept_set', schema='ontology')
    op.drop_table('region_relation', schema='geo')
    op.drop_table('region_set_shape', schema='geo')
    op.drop_table('region', schema='geo')
    op.drop_table('region_set', schema='geo')
    op.drop_table('col_set_member', schema='case')
    op.drop_table('col', schema='case')
    op.drop_table('case_type_set_member', schema='case')
    op.drop_table('case_set_member', schema='case')
    op.drop_table('case_set_data_collection_link', schema='case')
    op.drop_table('case_identifier', schema='case')
    op.drop_table('case_data_collection_link', schema='case')
    op.drop_table('tree_algorithm', schema='case')
    op.drop_table('ref_col', schema='case')
    op.drop_table('dim', schema='case')
    op.drop_table('case_type_set', schema='case')
    op.drop_table('case_set', schema='case')
    op.drop_table('case', schema='case')
    op.drop_table('tree_algorithm_class', schema='case')
    op.drop_table('ref_dim', schema='case')
    op.drop_table('genetic_distance_protocol', schema='case')
    op.drop_table('col_set', schema='case')
    op.drop_table('case_type_set_category', schema='case')
    op.drop_table('case_type', schema='case')
    op.drop_table('case_set_status', schema='case')
    op.drop_table('case_set_category', schema='case')
    op.drop_table('user_share_case_policy', schema='abac')
    op.drop_table('user_access_case_policy', schema='abac')
    op.drop_table('organization_share_case_policy', schema='abac')
    op.drop_table('organization_access_case_policy', schema='abac')
    # ### end Alembic commands ###
