[repository.defaults]
type = "DICT"

[repository.defaults.props]
dir="./data/seqdb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.dict.abac.empty.pkl.gz"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.dict.organization.empty.pkl.gz"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.dict.system.empty.pkl.gz"

[repository.seq.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.dict.seq.empty.pkl.gz"
