[repository.defaults]
type = "SA_SQLITE"

[repository.defaults.props]
dir="./data/seqdb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.abac.full.sqlite"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.organization.full.sqlite"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.system.full.sqlite"

[repository.seq.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.seq.full.sqlite"
