[repository.defaults]
type = "SA_SQLITE"

[repository.defaults.props]
dir="./data/seqdb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.abac.empty.sqlite"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.organization.empty.sqlite"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.system.empty.sqlite"

[repository.seq.props]
file = "@format {this.repository.defaults.props.dir}/seqdb.sa_sqlite.seq.empty.sqlite"
