from enum import Enum


class TestType(Enum):
    UNDEFINED = "UNDEFINED"
    COMMONDB_INTEGRATION_BUILD_DB = "COMMONDB_INTEGRATION_BUILD_DB"
    CASEDB_CUSTOM = "CASEDB_CUSTOM"
    CASEDB_INTEGRATION_BUILD_DB = "CASEDB_INTEGRATION_BUILD_DB"
    CASEDB_INTEGRATION_CASE_ACCESS = "CASEDB_INTEGRATION_CASE_ACCESS"
    CASEDB_INTEGRATION_CASE_VALIDATION = "CASEDB_INTEGRATION_CASE_VALIDATION"
    CASEDB_INTEGRATION_CONTENT = "CASEDB_INTEGRATION_CONTENT"
    CASEDB_PERFORMANCE_REPOSITORY = "CASEDB_PERFORMANCE_REPOSITORY"
    CASEDB_PERFORMANCE_USER_JOURNEY = "CASEDB_PERFORMANCE_USER_JOURNEY"
    CASEDB_PERFORMANCE_STARTUP = "CASEDB_PERFORMANCE_STARTUP"
    SEQDB_INTEGRATION_BUILD_DB = "SEQDB_INTEGRATION_BUILD_DB"
    DOCS_ERM = "DOCS_ERM"


class ServerType(Enum):
    COMMONDB = "COMMONDB"
    CASEDB = "CASEDB"
    SEQDB = "SEQDB"
    OMOPDB = "OMOPDB"
    OAUTH = "OAUTH"
    OAUTH_RECEIVER = "OAUTH_RECEIVER"


class ServerTypeSet(Enum):
    NON_AUTH = frozenset(
        {
            ServerType.COMMONDB,
            ServerType.CASEDB,
            ServerType.SEQDB,
            ServerType.OMOPDB,
        }
    )
    AUTH = frozenset({ServerType.OAUTH, ServerType.OAUTH_RECEIVER})
