from enum import Enum


class TestType(Enum):
    UNDEFINED = "UNDEFINED"
    CASEDB_CUSTOM = "CASEDB_CUSTOM"
    CASEDB_INTEGRATION_BUILD_DB = "CASEDB_INTEGRATION_BUILD_DB"
    CASEDB_INTEGRATION_CASE_ACCESS = "CASEDB_INTEGRATION_CASE_ACCESS"
    CASEDB_INTEGRATION_CONTENT = "CASEDB_INTEGRATION_CONTENT"
    CASEDB_PERFORMANCE_REPOSITORY = "CASEDB_PERFORMANCE_REPOSITORY"
    CASEDB_PERFORMANCE_USER_JOURNEY = "CASEDB_PERFORMANCE_USER_JOURNEY"
    CASEDB_PERFORMANCE_STARTUP = "CASEDB_PERFORMANCE_STARTUP"
    DOCS_ERM = "DOCS_ERM"
