[repository.defaults]
type = "SA_SQL"

[repository.defaults.props]
driver = "ODBC Driver 18 for SQL Server"
server = "127.0.0.1"
database = "DUMMY"
uid = "DUMMY"
pwd = "DUMMY"
other = ""
# other = ";TrustServerCertificate=yes"
# other = ";Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
connection_string = "mssql+pyodbc:///?odbc_connect=DRIVER={driver};SERVER={server};DATABASE={database};UID={uid};PWD={pwd}{other}"

[repository.abac.props]
connection_string = "@format mssql+pyodbc:///?odbc_connect=DRIVER={this.repository.defaults.props.driver};SERVER={this.repository.defaults.props.server};DATABASE={this.repository.defaults.props.database};UID={this.repository.defaults.props.uid};PWD={this.repository.defaults.props.pwd}{this.repository.defaults.props.other}"

[repository.organization.props]
connection_string = "@format mssql+pyodbc:///?odbc_connect=DRIVER={this.repository.defaults.props.driver};SERVER={this.repository.defaults.props.server};DATABASE={this.repository.defaults.props.database};UID={this.repository.defaults.props.uid};PWD={this.repository.defaults.props.pwd}{this.repository.defaults.props.other}"

[repository.system.props]
connection_string = "@format mssql+pyodbc:///?odbc_connect=DRIVER={this.repository.defaults.props.driver};SERVER={this.repository.defaults.props.server};DATABASE={this.repository.defaults.props.database};UID={this.repository.defaults.props.uid};PWD={this.repository.defaults.props.pwd}{this.repository.defaults.props.other}"

[repository.omop.props]
connection_string = "@format mssql+pyodbc:///?odbc_connect=DRIVER={this.repository.defaults.props.driver};SERVER={this.repository.defaults.props.server};DATABASE={this.repository.defaults.props.database};UID={this.repository.defaults.props.uid};PWD={this.repository.defaults.props.pwd}{this.repository.defaults.props.other}"
