[repository.defaults]
type = "DICT"

[repository.defaults.props]
dir="./data/omopdb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.abac.empty.pkl.gz"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.organization.empty.pkl.gz"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.system.empty.pkl.gz"

[repository.omop.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.omop.empty.pkl.gz"
