[repository.defaults]
type = "DICT"

[repository.defaults.props]
dir = "./data/omopdb/demo"

[repository.abac]
module = "gen_epix.omopdb.repositories"
class_name = "AbacDictRepository"
[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.abac.{this.repository.defaults.props.variant}.pkl.gz"

[repository.organization]
module = "gen_epix.omopdb.repositories"
class_name = "OrganizationDictRepository"
[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.organization.{this.repository.defaults.props.variant}.pkl.gz"

[repository.system]
module = "gen_epix.omopdb.repositories"
class_name = "SystemDictRepository"
[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.system.{this.repository.defaults.props.variant}.pkl.gz"

[repository.omop]
module = "gen_epix.omopdb.repositories"
class_name = "OmopDictRepository"
[repository.omop.props]
file = "@format {this.repository.defaults.props.dir}/omopdb.dict.omop.{this.repository.defaults.props.variant}.pkl.gz"
