version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '{"ts":"%(asctime)s","logger":"%(name)s","level":"%(levelname)s","content":%(message)s}'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  commondb.setup:
    level: INFO
    handlers: [console]
    propagate: no
  commondb.service:
    level: INFO
    handlers: [console]
    propagate: no
  commondb.app:
    level: INFO
    handlers: [console]
    propagate: no
  commondb.api:
    level: INFO
    handlers: [console]
    propagate: no
  commondb.external:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
