[[service.auth.props.idps_cfg]]
name = "mock"
label = "MOCK"
protocol = "OIDC"
discovery_url = "https://127.0.0.1:5443/.well-known/openid-configuration"
client_id = "mock"
client_secret = "mock"
scope = "openid profile email offline_access"

[service.auth.props.idps_cfg.claim_map]
__key__ = "email"
