[[service.auth.props.idps_cfg]]
name = "mock"
label = "MOCK"
protocol = "OIDC"
discovery_url = "https://127.0.0.1:5443/.well-known/openid-configuration"
client_id = "mock"
client_secret = "mock"
scope = "openid profile email"
public = true
enable_introspection = false
introspection_interval_seconds = 300
introspection_timeout_seconds = 2
introspection_auth_method = "client_secret_basic"

[service.auth.props.idps_cfg.claim_map]
__key__ = "sub"