[service.auth.props.automatic_new_user]
roles = ["ORG_USER"]

[service.auth.props.automatic_new_user.organization]
id = "018d074d-e9fc-b282-fcaa-377a752b95e5"
name = "DUMMY"

[service.auth.props.root.organization]
id = "018d074d-ea0c-e942-07db-a3cc0ba1d653"
name = "DUMMY"
legal_entity_code = "DUMMY"

[service.auth.props.root.user]
id = "019542cc-8225-8f5d-fa30-d9c3f2629703"
email = "root@dummy.org"

# TODO: remove if not used
[service.auth.props.commondb.user]
id = "019542cc-8225-8f5d-fa30-d9c3f2629703"
email = "root@dummy.org"
organization_id = "018d074d-ea0c-e942-07db-a3cc0ba1d653"
roles = ["APP_ADMIN"]
