[repository.defaults]
type = "DICT"

[repository.defaults.props]
dir="./data/commondb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.abac.empty.pkl.gz"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.organization.empty.pkl.gz"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.system.empty.pkl.gz"
