[repository.defaults]
type = "SA_SQLITE"

[repository.defaults.props]
dir="./data/commondb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.abac.empty.sqlite"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.organization.empty.sqlite"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/commondb.dict.system.empty.sqlite"
