[service.auth.props.automatic_new_user]
roles = ["ORG_USER"]

[service.auth.props.automatic_new_user.organization]
id = "018d074d-e9fc-b282-fcaa-377a752b95e5"
name = "DUMMY"

[service.auth.props.root.organization]
id = "01915051-eddd-132c-a5c5-d05672295291"
name = "DUMMY"
legal_entity_code = "DUMMY"

[service.auth.props.root.user]
id = "01915051-edde-f225-19d7-7ab8886e00bc"
email = "root@dummy.org"

# TODO: remove if not used
[service.auth.props.commondb.user]
id = "01915051-edde-f225-19d7-7ab8886e00bc"
email = "root@dummy.org"
organization_id = "01915051-eddd-132c-a5c5-d05672295291"
roles = ["APP_ADMIN"]
