[repository.defaults]
type = "SA_SQLITE"

[repository.defaults.props]
dir = "./data/commondb/demo"

[repository.abac.props]
file = "@format {this.repository.defaults.props.dir}/commondb.sa_sqlite.abac.{this.repository.defaults.props.variant}.sqlite"

[repository.organization.props]
file = "@format {this.repository.defaults.props.dir}/commondb.sa_sqlite.organization.{this.repository.defaults.props.variant}.sqlite"

[repository.system.props]
file = "@format {this.repository.defaults.props.dir}/commondb.sa_sqlite.system.{this.repository.defaults.props.variant}.sqlite"
