[repository.abac]
module = "gen_epix.commondb.repositories"
class_name = "AbacDictRepository"

[repository.organization]
module = "gen_epix.commondb.repositories"
class_name = "OrganizationDictRepository"

[repository.system]
module = "gen_epix.commondb.repositories"
class_name = "SystemDictRepository"
