name: release-please
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/p/gen-epix
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: googleapis/release-please-action@v4.2.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - uses: actions/checkout@v5
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Bump version in pyproject.toml
        run: |
          VERSION=${{ steps.release.outputs.new_version }}
          sed -i "s/^version = \".*\"/version = \"${VERSION}\"/" pyproject.toml
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump version in pyproject.toml to ${{ steps.release.outputs.new_version }}"
          commit_options: "--no-verify --signoff"
          file_pattern: "pyproject.toml"
          push_options: "--force"
          branch: main
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.13"
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Install build packages
        run: |
          python -m pip install --upgrade pip
          pip install build
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Build package distributions
        run: |
          python -m build --outdir dist
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Zip dist directory
        run: zip -r distribution-artifacts dist
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Upload release artifact to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} distribution-artifacts.zip
        if: ${{ (steps.release.outputs.release_created == 'true') }}

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
